### ISSUE TITLE
Could you share pretrained weight file for base training?

### ISSUE THREAD

**Issue by geonuk-kimmm** [jiaxi-wu/MPSR#11]
Thank you for releasing a source code.
Could you share a pretrained weight file for base classes particularly on Pascal VOC?

Thanks,

**Comment by jiaxi-wu** [comment]
Hi @mandal4 
I will run the code and share the pretrained weight files soon after I update the baseline part.

**Comment by geonuk-kimmm** [comment]
Thanks, i will wait for it.
