### ISSUE TITLE
objectness and label size unmatch in COCO

### ISSUE THREAD

**Issue by pppplin** [jiaxi-wu/MPSR#16]
While running your code on COCO, I find that objectness and label doesn't match in shape. For example, in https://github.com/jiaxi-wu/MPSR/blob/master/maskrcnn_benchmark/modeling/rpn/loss.py#L136 if I print out the objectness and labels shapes, I find that labels was longer than objectness. Any idea on what might cause this? Thanks

**Comment by jiaxi-wu** [comment]
Do you refer to the "objectness" and "labels", two variables defined by the original detection code?
They are not modified in this repo.
Would you offer more info?
