### ISSUE TITLE
can't reproduce VOC results

### ISSUE THREAD

**Issue by pppplin** [jiaxi-wu/MPSR#17]
Many thanks for your work! I tried to reproduce your results in VOC but failed to do so. I'm guessing I didn't initialize the novel classifier weights correctly, any suggestion? Would you please point / provide your function on transforming and fine-tuning base weights?

**Comment by jiaxi-wu** [comment]
Hi, 
model weight transforming script is `MPSR/tools/fewshot_exp/trans_voc_pretrained.py`. You can see the reinitialization is simple.

**Comment by pppplin** [comment]
thanks
