### ISSUE TITLE
Question about few-shot training samples

### ISSUE THREAD

**Issue by geonuk-kimmm** [jiaxi-wu/MPSR#2]
First, thanks for sharing a source code!

I see that you used training samples defined by [FSRW(ICCV 2019)](https://github.com/bingykang/Fewshot_Detection)
At this point, i'd like to ask you that training images for novel class is same with the [FSRW(ICCV 2019)](https://github.com/bingykang/Fewshot_Detection).

Specifically, i wish you could check if the 1-shot training image that you used for airplane is _datasets/VOC2012/JPEGImages/2008_006761.jpg_ and 1-shot training image that you used for bicycle is _datasets/VOC2012/JPEGImages/2009_005064.jpg_.

Thanks again for releasing nice paper and source code!

**Comment by jiaxi-wu** [comment]
Hello, thanks for your interest.

Yes, I'm using training samples defined in [FSRW/data](https://github.com/bingykang/Fewshot_Detection/tree/master/data) for the final evaluation. 
These two images you metioned are in the 1-shot training set indeed.

**Comment by geonuk-kimmm** [comment]
Thanks for your reply.
Did you exclude the ‘difficult==True’ labeled instances in the selected samples?
I found that without excluding the difficult instances, the samples could represent more than K-shot.

**Comment by jiaxi-wu** [comment]
Of course we did it and that's default setting even not in few-shot experiments.
You can refer to [maskrcnn-benchmak/data/build.py#L41](https://github.com/jiaxi-wu/MPSR/blob/abc259b05437c546e545510ef2a5d70aa1a4ea06/maskrcnn_benchmark/data/build.py#L41).

Hope this will help you.
