### ISSUE TITLE
Crops Improvement

### ISSUE THREAD

**Issue by Ze-Yang** [jiaxi-wu/MPSR#6]
Hi, from my view, I see that the crops generation process contains no randomness, hence no need to generate it every time you run the training. Maybe you can improve it, just suggestion. Thanks.

**Comment by jiaxi-wu** [comment]
Actually,  they are fixed since we only provide the FSRW datasplit for evaluation. But we are using other datasplit series during arch designing and parameter tuning. I've updated them which are different in every class-split. 
Hope this will help your for further research.

**Comment by Ze-Yang** [comment]
Thanks for your info.
